#!/usr/bin/env python3
"""
make_team_configs.py  --  regenerate GP1's per-team sensor rigs.

Each team gets a different vehicle, spawn point, LiDAR mount, camera mount
and camera pitch. Because the Task 5 extrinsic is fully determined by that
geometry, every team's answer is a different matrix, so a solution copied
from another team, from a previous cohort, or from this repository's git
history produces a measurably wrong overlay.

Run it once per semester with a new --year. The seed is derived from the
year, so the same year always reproduces the same table (handy if you need
to regrade), and a different year gives a completely different one.

    # print the table
    python3 tools/make_team_configs.py --year 2027 --teams 10

    # write it straight into gp1.rst, between the marker comments
    python3 tools/make_team_configs.py --year 2027 --teams 10 --inject

    # what each team's answer should be, for grading
    python3 tools/make_team_configs.py --year 2027 --teams 10 --answers
"""

import argparse
import pathlib
import re
import sys

import numpy as np

VEHICLES = [
    "vehicle.tesla.model3", "vehicle.audi.a2", "vehicle.bmw.grandtourer",
    "vehicle.citroen.c3", "vehicle.dodge.charger_2020", "vehicle.ford.mustang",
    "vehicle.jeep.wrangler_rubicon", "vehicle.lincoln.mkz_2020",
    "vehicle.mercedes.coupe_2020", "vehicle.nissan.patrol_2021",
    "vehicle.seat.leon", "vehicle.toyota.prius", "vehicle.chevrolet.impala",
    "vehicle.mini.cooper_s", "vehicle.nissan.micra", "vehicle.audi.tt",
]
RESOLUTIONS = [(1280, 720), (1600, 900), (1920, 1080), (1024, 576)]
FOVS = [72, 90, 100, 110]

BEGIN = ".. GP1-TEAM-CONFIG-BEGIN (generated by tools/make_team_configs.py)"
END = ".. GP1-TEAM-CONFIG-END"

# body -> optical: x right, y down, z forward
P_OPTICAL = np.array([[0, 1, 0], [0, 0, -1], [1, 0, 0]], dtype=float)


def build(year: int, n_teams: int):
    rng = np.random.default_rng(year)
    vehicles = list(VEHICLES)
    rng.shuffle(vehicles)
    teams = []
    for i in range(n_teams):
        teams.append({
            "id": chr(65 + i) if n_teams <= 26 else str(i + 1),
            "vehicle": vehicles[i % len(vehicles)],
            "spawn": int(rng.integers(0, 60)),
            "lidar": (round(float(rng.uniform(-0.4, 0.4)), 2), 0.0,
                      round(float(rng.uniform(2.4, 3.0)), 2)),
            "channels": int(rng.choice([32, 64])),
            "camera": (round(float(rng.uniform(1.0, 2.2)), 2),
                       round(float(rng.uniform(-0.4, 0.4)), 2),
                       round(float(rng.uniform(1.3, 1.9)), 2)),
            "pitch": round(float(rng.uniform(-12, 4)), 1),
            "res": RESOLUTIONS[i % len(RESOLUTIONS)],
            "fov": int(rng.choice(FOVS)),
        })
    return teams


def extrinsic(t) -> np.ndarray:
    """The T_cam_lidar each team should arrive at. Grading reference."""
    th = np.radians(t["pitch"])
    r_mount = np.array([[np.cos(th), 0, np.sin(th)],
                        [0, 1, 0],
                        [-np.sin(th), 0, np.cos(th)]])
    rot = P_OPTICAL @ r_mount.T
    delta = np.array(t["camera"]) - np.array(t["lidar"])
    trans = -rot @ delta.reshape(3, 1)
    return np.vstack([np.hstack([rot, trans]), [0, 0, 0, 1]])


def as_rst(teams) -> str:
    out = [
        ".. list-table::",
        "   :widths: 8 26 8 22 20 16",
        "   :header-rows: 1",
        "   :class: compact-table",
        "",
        "   * - **Team**",
        "     - **Vehicle blueprint**",
        "     - **Spawn**",
        "     - **LiDAR (x, y, z) / channels**",
        "     - **Camera (x, y, z) / pitch**",
        "     - **Image / FOV**",
    ]
    for t in teams:
        lx, ly, lz = t["lidar"]
        cx, cy, cz = t["camera"]
        w, h = t["res"]
        out += [
            f"   * - {t['id']}",
            f"     - ``{t['vehicle']}``",
            f"     - {t['spawn']}",
            f"     - ({lx}, {ly}, {lz}) / {t['channels']}",
            f"     - ({cx}, {cy}, {cz}) / {t['pitch']} deg",
            f"     - {w}x{h} / {t['fov']} deg",
        ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--year", type=int, required=True,
                    help="seeds the table; use the course year")
    ap.add_argument("--teams", type=int, default=10)
    ap.add_argument("--answers", action="store_true",
                    help="print each team's expected extrinsic, for grading")
    ap.add_argument("--inject", action="store_true",
                    help="rewrite the table inside gp1.rst in place")
    ap.add_argument("--gp1", default="docs/source/assignments/gp1.rst")
    args = ap.parse_args()

    teams = build(args.year, args.teams)

    if args.answers:
        np.set_printoptions(precision=3, suppress=True)
        for t in teams:
            print(f"--- Team {t['id']}  ({t['vehicle']}, pitch {t['pitch']} deg)")
            print(extrinsic(t), "\n")
        return 0

    table = as_rst(teams)

    if not args.inject:
        print(table)
        return 0

    path = pathlib.Path(args.gp1)
    text = path.read_text()
    if BEGIN not in text or END not in text:
        print(f"error: markers not found in {path}. Expected:\n"
              f"  {BEGIN}\n  {END}", file=sys.stderr)
        return 1
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        BEGIN + "\n\n" + table + "\n\n" + END,
        text, flags=re.S)
    path.write_text(new)
    print(f"injected {len(teams)} teams into {path} (year {args.year})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
